services:
  web:
    build:
      context: .  # Utilise le répertoire courant comme contexte pour la construction de l'image
      dockerfile: Dockerfile
    image: visit-scotland-nginx:1.0  # Nom de l'image perso construite
    container_name: ${CONTAINER_NAME} # Nom du conteneur -> .env
    ports:
      - "${HOST_PORT}:80"  # Mappe le port 80 du conteneur au port 8080 de l'hôte -> .env
    volumes:
      - ../site:/usr/share/nginx/html
    networks:
      - web-dev-exam

networks:
  web-dev-exam:
    driver: bridge
